import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
import questionpapergernerator.QuestionPaperGernerator;
public class paper extends javax.swing.JFrame {

    /**
     * Creates new form paper
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps  = null;
    public paper() {
        initComponents();
        conn = QuestionPaperGernerator.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnGroupMarks = new javax.swing.ButtonGroup();
        jbtnGroupMode = new javax.swing.ButtonGroup();
        jPanelParent = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jbtnViewQuestion = new javax.swing.JButton();
        jbtnGeneratePaper = new javax.swing.JButton();
        jbtnAddQuestion = new javax.swing.JButton();
        jPanelAdd = new javax.swing.JPanel();
        jtxtChapterName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtQuestions = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jtxtMarks = new javax.swing.JTextField();
        jcbDifficulty = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jPanelView = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jPanelQuestionTypeSelction = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jbtnNext = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jPanelParentSegregation = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jTextChoice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcb10 = new javax.swing.JComboBox();
        jcb5 = new javax.swing.JComboBox();
        jcb3 = new javax.swing.JComboBox();
        jcb2 = new javax.swing.JComboBox();
        jcb1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        cBtn10 = new javax.swing.JButton();
        cbtn5 = new javax.swing.JButton();
        cbtn3 = new javax.swing.JButton();
        cbtn2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelQuestionView = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jbtnGenerate = new javax.swing.JButton();
        jbtnReload = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelParent.setLayout(new java.awt.CardLayout());

        jbtnViewQuestion.setText("View Question");
        jbtnViewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewQuestionActionPerformed(evt);
            }
        });

        jbtnGeneratePaper.setText("Generate Paper");
        jbtnGeneratePaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGeneratePaperActionPerformed(evt);
            }
        });

        jbtnAddQuestion.setText("Add Question");
        jbtnAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnViewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnGeneratePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(171, Short.MAX_VALUE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jbtnAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jbtnViewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbtnAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtnGeneratePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelHome, "card2");

        jtxtChapterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChapterNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Chapter Number");

        jLabel2.setText("Question");

        jtxtQuestions.setColumns(20);
        jtxtQuestions.setRows(5);
        jScrollPane1.setViewportView(jtxtQuestions);

        jLabel3.setText("Marks");

        jcbDifficulty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "easy", "medium", "hard" }));
        jcbDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDifficultyActionPerformed(evt);
            }
        });

        jLabel4.setText("Difficulty");

        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtChapterName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jtxtMarks)
                    .addComponent(jcbDifficulty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(229, 229, 229))
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtChapterName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelAdd, "card3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(80, 80, 80))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanelParent.add(jPanelView, "card4");

        jLabel5.setText("Total Marks");

        jbtnGroupMarks.add(jRadioButton1);
        jRadioButton1.setText("10");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jbtnGroupMarks.add(jRadioButton2);
        jRadioButton2.setText("15");

        jbtnGroupMarks.add(jRadioButton3);
        jRadioButton3.setText("20");

        jbtnGroupMarks.add(jRadioButton4);
        jRadioButton4.setText("30");

        jbtnGroupMarks.add(jRadioButton5);
        jRadioButton5.setText("50");

        jbtnGroupMode.add(jRadioButton6);
        jRadioButton6.setText("ChapterWise");

        jbtnGroupMode.add(jRadioButton7);
        jRadioButton7.setText("Difficulty");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jbtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (3).png"))); // NOI18N
        jbtnNext.setText("Next");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-resizeimage.png"))); // NOI18N
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuestionTypeSelctionLayout = new javax.swing.GroupLayout(jPanelQuestionTypeSelction);
        jPanelQuestionTypeSelction.setLayout(jPanelQuestionTypeSelctionLayout);
        jPanelQuestionTypeSelctionLayout.setHorizontalGroup(
            jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)))
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnBack)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanelQuestionTypeSelctionLayout.setVerticalGroup(
            jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1))
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jRadioButton6)))
                .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanelQuestionTypeSelctionLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButton7)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(jPanelQuestionTypeSelctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPanelParent.add(jPanelQuestionTypeSelction, "card5");

        jlblTitle.setText("jLabel6");

        jTextChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChoiceActionPerformed(evt);
            }
        });

        jLabel7.setText("10 Marks");

        jLabel8.setText("5 Marks");

        jLabel9.setText("3 Marks");

        jLabel10.setText("2 Marks");

        jLabel11.setText("1 Marks");

        jcb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb10ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh-resizeimage.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cBtn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        cBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBtn10ActionPerformed(evt);
            }
        });

        cbtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        cbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtn5ActionPerformed(evt);
            }
        });

        cbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        cbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtn3ActionPerformed(evt);
            }
        });

        cbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        cbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtn2ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (2).png"))); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-resizeimage.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParentSegregationLayout = new javax.swing.GroupLayout(jPanelParentSegregation);
        jPanelParentSegregation.setLayout(jPanelParentSegregationLayout);
        jPanelParentSegregationLayout.setHorizontalGroup(
            jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jTextChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(177, 177, 177)
                                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcb3, 0, 69, Short.MAX_VALUE)
                                            .addComponent(jcb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcb10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                    .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcb1, 0, 69, Short.MAX_VALUE)
                                        .addComponent(jcb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(246, 246, 246)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParentSegregationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelParentSegregationLayout.setVerticalGroup(
            jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParentSegregationLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(cBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtn2))
                        .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanelParentSegregationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(164, 164, 164))
                            .addGroup(jPanelParentSegregationLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParentSegregationLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelParentSegregation, "card6");

        jTableQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableQuestions);

        jbtnGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Generate-resizeimage (2).png"))); // NOI18N
        jbtnGenerate.setText("Generate Paper");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        jbtnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh-resizeimage.png"))); // NOI18N
        jbtnReload.setText("Reload");
        jbtnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReloadActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-resizeimage.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuestionViewLayout = new javax.swing.GroupLayout(jPanelQuestionView);
        jPanelQuestionView.setLayout(jPanelQuestionViewLayout);
        jPanelQuestionViewLayout.setHorizontalGroup(
            jPanelQuestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
            .addGroup(jPanelQuestionViewLayout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jbtnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanelQuestionViewLayout.setVerticalGroup(
            jPanelQuestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionViewLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelQuestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuestionViewLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelQuestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuestionViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanelParent.add(jPanelQuestionView, "card3");

        getContentPane().add(jPanelParent, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGeneratePaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGeneratePaperActionPerformed
          jPanelParent.removeAll();
        jPanelParent.add(jPanelQuestionTypeSelction);
        jPanelParent.revalidate();
    }//GEN-LAST:event_jbtnGeneratePaperActionPerformed

    private void jbtnAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddQuestionActionPerformed
        // TODO add your handling code here:
        jPanelParent.removeAll();
        jPanelParent.add(jPanelAdd);
        jPanelParent.revalidate();
        
    }//GEN-LAST:event_jbtnAddQuestionActionPerformed

    private void jtxtChapterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChapterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChapterNameActionPerformed

    private void jcbDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDifficultyActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try{
            String sql = "Insert into questions(chapter_id, question, marks, difficulty) VALUES (?,?,?,?)";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(jtxtChapterName.getText()));
            ps.setString(2, jtxtQuestions.getText());
            ps.setInt(3, Integer.parseInt(jtxtMarks.getText()));
            int a = jcbDifficulty.getSelectedIndex();
            ps.setInt(4, a);
            boolean stmt = ps.execute();
            JOptionPane.showMessageDialog(null, "Record inserted successfully!");
            clearFields();
            
        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Issue: " + se);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnViewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewQuestionActionPerformed
        jPanelParent.removeAll();
        jPanelParent.add(jPanelView);
        jPanelParent.revalidate();
        try{
            String sql = "select * from questions";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Issue: " + e);
        }finally{
            try{
                rs.close();
                ps.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedstatement");
            }
        }
    }//GEN-LAST:event_jbtnViewQuestionActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        for(Enumeration<AbstractButton> buttons = jbtnGroupMarks.getElements(); buttons.hasMoreElements(); ){
            AbstractButton button = buttons.nextElement();
            if(button.isSelected())
                totalMarks = Integer.parseInt(button.getText());
        }
        for(Enumeration<AbstractButton> buttons = jbtnGroupMode.getElements(); buttons.hasMoreElements(); ){
            AbstractButton button = buttons.nextElement();
            if(button.isSelected())
                choice = button.getText();
        }
        if(totalMarks == 0)
            JOptionPane.showMessageDialog(null, "Select the total marks ");
        else if(choice == null)
            JOptionPane.showMessageDialog(null, "Select your choice");
        else{
            jPanelParent.removeAll();
            if(choice == "Difficulty")
                jlblTitle.setText("Enter difficulty level: ");
            else if(choice == "ChapterWise")
                jlblTitle.setText("Enter chapter numbers: ");
            setMarks();
            jPanelParent.add(jPanelParentSegregation);
            jPanelParent.revalidate();
                
                 
        }
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jPanelParent.removeAll();
        jPanelParent.add(jPanelHome);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        jPanelParent.removeAll();
        jPanelParent.add(jPanelHome);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanelParent.removeAll();
        jPanelParent.add(jPanelQuestionTypeSelction);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void cBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtn10ActionPerformed
        int no = Integer.valueOf(jcb10.getSelectedItem()+"");
        int marks = 10*no;
        no10 = no;
        int count = calcNumber(marks,5);
        jcb5.enable();
        cbtn5.enable();
        for(int i = 0 ; i<=count;i++){
            jcb5.addItem(String.valueOf(i));
        }    
    }//GEN-LAST:event_cBtn10ActionPerformed

    private void cbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtn5ActionPerformed
      int no = Integer.valueOf(jcb5.getSelectedItem()+"");
        int marks = 5*no;
        no5 = no;
        int count = calcNumber(marks,3);
        jcb3.enable();
        cbtn3.enable();
        for(int i = 0 ; i<=count;i++){
            jcb3.addItem(String.valueOf(i));
        }    
    }//GEN-LAST:event_cbtn5ActionPerformed

    private void cbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtn3ActionPerformed
       int no = Integer.valueOf(jcb3.getSelectedItem()+"");
        int marks = 3*no;
        no3 = no;
        int count = calcNumber(marks,2);
        jcb2.enable();
        cbtn2.enable();
        for(int i = 0 ; i<=count;i++){
            jcb2.addItem(String.valueOf(i));
        }    
    }//GEN-LAST:event_cbtn3ActionPerformed

    private void cbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtn2ActionPerformed
        int no = Integer.valueOf(jcb2.getSelectedItem()+"");
        int marks = 2*no;
        no2 = no;
        int count = calcNumber(marks,1);
        jcb1.enable();
        
        jcb1.addItem(String.valueOf(count));
         
    }//GEN-LAST:event_cbtn2ActionPerformed

    private void jcb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb10ActionPerformed
    void refreshFields(){
        no1 = no2 = no3 = no5 = no10 = sum = 0;
        jcb1.setSelectedIndex(-1);
        jcb2.setSelectedIndex(-1);
        jcb3.setSelectedIndex(-1);
        jcb5.setSelectedIndex(-1);
        jcb10.setSelectedIndex(-1);
        jcb5.disable();
        jcb3.disable();
        jcb2.disable();
        jcb1.disable();
        cbtn5.disable();
        cbtn3.disable();
        cbtn2.disable();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             refreshFields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.out.println("\nClicked Submit");
        makeRelevantTable();
        jPanelParent.removeAll();
        jPanelParent.add(jPanelQuestionView);
        jPanelParent.revalidate();
        
        try{
            String sql = "select * from relevantquestions";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            jTableQuestions.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Issue: " + e);
        }finally{
            try{
                rs.close();
                ps.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedstatement");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChoiceActionPerformed

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
       try{
        String sql = "Update questions set probability = probability + 1 where question_id in (Select question_id from relevantquestions where 1)";
       ps = conn.prepareStatement(sql);
       ps.executeUpdate();
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Problem i updating probabilty " + e);
       }
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    private void jbtnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReloadActionPerformed
        makeRelevantTable();
         try{
            String sql = "select * from relevantquestions";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            jTableQuestions.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Issue: " + e);
        }finally{
            try{
                rs.close();
                ps.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedstatement");
            }
        }
    }//GEN-LAST:event_jbtnReloadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanelParent.removeAll();
        jPanelParent.add(jPanelParentSegregation);
        jPanelParent.repaint();
        refreshFields();
    }//GEN-LAST:event_jButton3ActionPerformed
    void clearFields(){
        jtxtChapterName.setText("");
        jtxtQuestions.setText("");
        jtxtMarks.setText("");
        jcbDifficulty.setSelectedIndex(-1);
    }
    void setMarks(){
        int marks = totalMarks;
        marks = marks/10;
        jcb10.removeAllItems();
        for(int i = 0 ; i <= marks; i++){
            jcb10.addItem(String.valueOf(i));
        }
        jcb5.disable();
        jcb3.disable();
        jcb2.disable();
        jcb1.disable();
        cbtn5.disable();
        cbtn3.disable();
        cbtn2.disable();
        

    }
    int calcNumber(int marks, int n){
        sum = sum+marks;
        if(sum<totalMarks){
            int diff = totalMarks-sum;
            return (diff/n);
        }
        return 0;
            
    }
    void makeRelevantTable(){
        try{
            System.out.println("\nInside Making tabes");
            int diff = 0;
            String sql = "Truncate relevantquestions";
            ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            System.out.println("choice: "+choice);
            if(choice == "Difficulty"){
                if(jTextChoice.getText().equals("easy"))
                    diff = 1;
                else if(jTextChoice.getText().equals("difficult"))
                    diff = 3;
                else
                    diff = 2;
                
            System.out.println("\nDifficulty: "+ diff);
            System.out.println("\n Number 10 : " + no10);
            if(no2!=0){
                String sql10 = "Insert into relevantquestions Select * from questions where marks = 10 and difficulty = "+ diff+ " order by probability asc, rand() limit " + no10;
                 ps = conn.prepareStatement(sql10);
                 ps.executeUpdate();
            }
            if(no5!=0){
                String sql5 = "Insert into relevantquestions Select * from questions where marks = 5 and difficulty = "+ diff+ " order by probability asc, rand() limit " + no5;
                ps = conn.prepareStatement(sql5);
                ps.executeUpdate();
            }
            if(no3!=0){
                String sql3 = "Insert into relevantquestions Select * from questions where marks = 3 and difficulty = "+ diff+ " order by probability asc, rand() limit " + no3;
                ps = conn.prepareStatement(sql3);
                ps.executeUpdate();
            }
            if(no2!=0){
                String sql2 = "Insert into relevantquestions Select * from questions where marks = 2 and difficulty = "+ diff+ " order by probability asc, rand() limit " + no2;
                ps = conn.prepareStatement(sql2);
                ps.executeUpdate();
            }
            if(no1!=0){
                String sql1 = "Insert into relevantquestions Select * from questions where marks = 1 and difficulty = "+ diff+ " order by probability asc, rand() limit " + no1;
                ps = conn.prepareStatement(sql1);
                ps.executeUpdate();
            }
            }else if(choice == "ChapterWise"){
                String chapters = jTextChoice.getText();
                String chps[] = chapters.split(",");
                if(no2!=0){
                    String sql10 = "Insert into relevantquestions Select * from questions where marks = 10 and chapter_id IN ("+ chapters+") order by probability asc, rand() limit " + no10;
                    ps = conn.prepareStatement(sql10);
                    int n =  ps.executeUpdate();
                }
                if(no5!=0){
                    String sql5 = "Insert into relevantquestions Select * from questions where marks = 5 and chapter_id IN ("+ chapters+") order by probability asc, rand() limit " + no5;
                    ps = conn.prepareStatement(sql5);
                    ps.executeUpdate();
                }
                if(no3!=0){
                    String sql3 = "Insert into relevantquestions Select * from questions where marks = 3 and chapter_id IN ("+ chapters+") order by probability asc, rand() limit " + no3;
                    ps = conn.prepareStatement(sql3);
                    ps.executeUpdate();
                }
                if(no2!=0){
                    String sql2 = "Insert into relevantquestions Select * from questions where marks = 2 and dchapter_id IN ("+ chapters+") order by probability asc, rand() limit " + no2;
                    ps = conn.prepareStatement(sql2);
                    ps.executeUpdate();
                }
                if(no1!=0){
                    String sql1 = "Insert into relevantquestions Select * from questions where marks = 1 and chapter_id IN ("+ chapters+") order by probability asc, rand() limit " + no1;
                    ps = conn.prepareStatement(sql1);
                    ps.executeUpdate();
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problem in making relevant table" + e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBtn10;
    private javax.swing.JButton cbtn2;
    private javax.swing.JButton cbtn3;
    private javax.swing.JButton cbtn5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelParentSegregation;
    private javax.swing.JPanel jPanelQuestionTypeSelction;
    private javax.swing.JPanel jPanelQuestionView;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTextField jTextChoice;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnAddQuestion;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JButton jbtnGeneratePaper;
    private javax.swing.ButtonGroup jbtnGroupMarks;
    private javax.swing.ButtonGroup jbtnGroupMode;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnReload;
    private javax.swing.JButton jbtnViewQuestion;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JComboBox jcb10;
    private javax.swing.JComboBox jcb2;
    private javax.swing.JComboBox jcb3;
    private javax.swing.JComboBox jcb5;
    private javax.swing.JComboBox jcbDifficulty;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtxtChapterName;
    private javax.swing.JTextField jtxtMarks;
    private javax.swing.JTextArea jtxtQuestions;
    // End of variables declaration//GEN-END:variables
    int totalMarks;
    String choice;
    int sum = 0;
    int no10, no5, no3, no2, no1;
}
